---
title: "McDonalds OR"
author: "Mariia, Ai, Mauricio"
date: "2023-03-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE, warning=FALSE}
library(leaflet)
library(tidyverse)
library(readxl)
library(writexl)
library(dplyr)
```

```{r}
#load in data
mc <- read.csv("Data/menu.csv")

price <- read.csv("Data/prices.csv")

no_brekky <- mc %>%
  filter(mc$Category != "Breakfast")

no_brekky_small_bev <- no_brekky[!grepl("Small", no_brekky$Item), ]
no_brekky_large_bev <- no_brekky_small_bev[!grepl("Large", no_brekky_small_bev$Item), ]
no_brekky_child_bev <- no_brekky_large_bev[!grepl("Child", no_brekky_large_bev$Item), ]
no_brekky_kids_bev <- no_brekky_child_bev[!grepl("Kids", no_brekky_child_bev$Item), ]
no_brekky_snack_bev <- no_brekky_kids_bev[!grepl("Snack", no_brekky_kids_bev$Item), ]

df <- no_brekky_snack_bev

df$Item <- gsub("\\(Medium\\)", "", df$Item)

df <- left_join(df, price, by = "Item")

df$Price <- gsub("\\$", "", df$Price)

df$Price <- ifelse(grepl("McFlurry", df$Item), 4.29, df$Price)
df$Price <- ifelse(grepl("Shake|Smoothie", df$Item), 3.69, df$Price)
df$Price <- ifelse(grepl("Mocha", df$Item), 3.49, df$Price)
df$Price <- ifelse(grepl("Latte|Minute", df$Item), 3.29, df$Price)
df$Price <- ifelse(grepl("Tea|Milk|Dasani", df$Item), 1.49, df$Price)
df$Price <- ifelse(grepl("Sprite|Dr|Coke|Cola", df$Item), 1.79, df$Price)
df$Price <- ifelse(grepl("Iced", df$Item) & grepl("Coffee", df$Item), 2.69, df$Price)
df$Price <- ifelse(grepl("Hot Chocolate", df$Item), 2.79, df$Price)
df$Price <- ifelse(grepl("Sundae", df$Item), 3.49, df$Price)
df$Price <- ifelse(grepl("Frappé", df$Item), 3.99, df$Price)
df$Price <- ifelse(grepl("Cookie", df$Item), 1.99, df$Price)
df$Price <- ifelse(grepl("Southwest", df$Item) & grepl("Salad", df$Item), 
                   5.51, df$Price)
df$Price <- ifelse(grepl("Bacon", df$Item) & grepl("Salad", df$Item), 
                   5.28, df$Price)

df$Price[c(2:3, 5:6, 16, 18, 37:42, 49:51, 53, 71)] <- c(5.19, 6.19, 5.69, 7.09, 
                                                         4.79, 5.59, 1.89, 2.50, 
                                                         5.16, 6.89, 12.39, 4.89, 
                                                         3.59, 1.99, 0.89, 1.59, 
                                                         1.99)

#drop NAs
df <- df[complete.cases(df$Price),]

#drop apple juice
df <- df[-43,]

df <- df %>%
  mutate(Drink = NA) 

# put 1 for drinks, 0 for the rest
df$Drink[36:85] <- 1
df$Drink[1:35] <- 0

# convert the unit for calcium from %DV to mg
df$Calcium <- df$Calcium....Daily.Value.*(1300/100)
df$Iron <- df$Iron....Daily.Value.*(18/100)
```

```{r}
#export
write.csv(df, "Data/menu_prices.csv", row.names=FALSE)
```

```{r}
o=as.list(as.numeric((df$Price))) # define objective function for Price
c=matrix(c(df$Calories,
            df$Carbohydrates,
            df$Protein,
            df$Dietary.Fiber,
            df$Sodium,
            df$Iron,
            df$Total.Fat....Daily.Value.,
            df$Saturated.Fat....Daily.Value.,
            df$Calcium,
            df$Cholesterol,
            df$Drink),
           ncol = 85, 
           byrow=T) # matrix of coefficients for constraints

d = c("<=", ">=", ">=", ">=", "<=", ">=", "<=","<=", "<=","<=",">=") #constraints

r = c(2000/3, 130/3, 46/3, 28/3, 2300/3, 18/3, 35/3,10/3,1300/3,100, 1) # RHS of constraints

sol = lpSolve::lp("min",o,c,d,r,compute.sens=T) #find the optimal solution 
sol$solution

index <- which(sol$solution != 0)

coeffs <- data.frame(sol$solution[index])

coeffs <- coeffs %>%
  mutate(items = df$Item[index])
```


